- name: Install this role on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"

- name: NPM Install PM2,M Module
  shell:
    name: [pm2 n inherits]
    global: yes

- name: Check Node.js Version
  shell: sudo sh -c 'echo "Node.js versio is $(node -v)" 1>> /data/logs/install_version.txt'
