- name: Install this role on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"

- name: Install nvm 
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v{{nodejs_nvm_version}}/install.sh | bash
  args:
    creates: "/etc/profile.d/nvm.sh"

- name: Install Node.js,npm and yarn  
  shell: |
    source /etc/profile.d/nvm.sh
    nvm install {{nodejs_version}} 
    nvm use {{nodejs_version}} 
    npm install -g yarn
    npm install pm2 n inherits -g
    source /root/.bash_profile
  args:
    executable: /bin/bash

- name: Install Node.js applications
  include_tasks: apps_{{item}}.yml
  with_items: "{{nodejs_applications}}"
  when: nodejs_applications is defined and nodejs_applications is not none and nodejs_applications != "" and nodejs_applications[0]!= ""

- name: Check Node.js Version
  shell: sudo sh -c 'echo "Node.js version is $(node -v)" 1>> /data/logs/install_version.txt'
