- name: Install this role on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"

- name: NPM Install Modules
  shell: npm install pm2 n inherits -g

- name: Check Node.js Version
  shell: sudo sh -c 'echo "Node.js versio is $(node -v)" 1>> /data/logs/install_version.txt'
