- name: Install this role on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"

- name: Create nvm directory
  file:
    path: /opt/nvm
    state: directory
  
- name: Install nvm 
  shell: |
    export NVM_DIR=/opt/nvm
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v{{nodejs_nvm_version}}/install.sh | bash

- name: Install Node.js,npm and yarn  
  shell: |
    source {{ ansible_env.HOME }}/.bashrc
    nvm install {{nodejs_version}} 
    nvm use {{nodejs_version}} 
    npm install -g yarn
    npm install pm2 n inherits -g 
  args:
    executable: /bin/bash

- name: Create link
  file:
    src: '/opt/nvm/versions/node/v*/bin/{{item}}'
    dest: '/usr/bin/'
    state: link
    force: yes
  with_items: ["n","node","npm","npx","pm2","pm2-dev","pm2-docker","pm2-runtime","yarn","yarnpkg"]
   
- name: Install Node.js applications
  include_tasks: apps_{{item}}.yml
  with_items: "{{nodejs_applications}}"
  when: nodejs_applications is defined and nodejs_applications is not none and nodejs_applications != "" and nodejs_applications[0]!= ""

- name: Check Node.js Version
  shell: sudo echo "Node.js version is" $(node -v) |sudo tee -a /data/logs/install_version.txt
