- name: Install Express Generator
  npm:
    name: "{{ item }}"
    global: yes
    path: /data/wwwroot
  with_items:
    - express-generator 
    - express

# don't use www.example.com which will be removed by 9Panel
- name: Create express Demo Project
  shell: |
    test -d express && rm -rf express
    express express
  args:
    chdir: /data/wwwroot/

- name: Install Demo Project module
  shell: |
    npm install 
    pm2 start bin/www
    pm2 save
    pm2 startup
  args:
    chdir: /data/wwwroot/express

- name: Start pm2 
  service:
    name: pm2-root
    state: restarted
    enabled: yes
